name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_IDS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Trivy SAST scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          path: .

      - name: Build Docker image
        run: |
          cd ./dummy-app
          docker build -t ${{ secrets.AWS_ECR_REGISTRY }}:${{ github.sha }} .

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1

      - name: Push Docker image to ECR
        run: |
          docker tag ${{ secrets.AWS_ECR_REGISTRY }}:${{ github.sha }} ${{ secrets.AWS_ECR_REGISTRY }}:latest
          docker push ${{ secrets.AWS_ECR_REGISTRY }}:${{ github.sha }}
          docker push ${{ secrets.AWS_ECR_REGISTRY }}:latest

