name: CI/CD Pipeline

on:
  # Configure the pipeline to trigger on `pull_request` events targeting the `master` branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_IDS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Run a security scan (SAST) on the application code
      - name: Run Trivy SAST scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          path: .

      # Build a Docker image for a dummy application
      - name: Build Docker image
        run: |
          cd ./dummy-app
          docker build -t ${{ secrets.AWS_ECR_URI }}:${{ github.sha }} .

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      # Push the Docker image to Amazon ECR
      - name: Push Docker image to ECR
        run: |
          docker tag ${{ secrets.AWS_ECR_URI }}:${{ github.sha }} ${{ secrets.AWS_ECR_URI }}:latest
          docker push ${{ secrets.AWS_ECR_URI }}:${{ github.sha }}
      
      # Update the Argo CD manifest files with the new image tag
      - name: Update Argo CD manifest for frontend
        run: |
          echo "Contents of frontend-deployment.yaml before update:"
          cat ArgoCD/Frontend/frontend-deployment.yaml
          sed -i 's|image: .*|image: ${{ secrets.AWS_ECR_URI }}:${{ github.sha }}|' ArgoCD/Frontend/frontend-deployment.yaml
          echo "Contents of frontend-deployment.yaml after update:"
          cat ArgoCD/Frontend/frontend-deployment.yaml

      - name: Update Argo CD manifest for backend
        run: |
          echo "Contents of ArgoCD/backend.yaml before update:"
          cat ArgoCD/Backend/backend-deployment.yaml
          sed -i 's|image: .*|image: ${{ secrets.AWS_ECR_URI }}:${{ github.sha }}|' ArgoCD/Backend/backend-deployment.yaml
          echo "Contents of backend-deployment.yaml after update:"
          cat ArgoCD/Backend/backend-deployment.yaml

      # Commit and push these changes 
      - name: Commit updated manifest files
        run: |
          git config user.email ${{ secrets.GIT_USER_EMAIL}}
          git config user.name ${{ secrets.GIT_USER }}
          git add ArgoCD/Frontend/frontend-deployment.yaml
          git add ArgoCD/Backend/backend-deployment.yaml
          git commit -m "Update Argo CD manifests with new image tag"
          git push

      # Trigger Argo CD to sync the updated manifests
      - name: Trigger Argo CD sync
        run: |
          argocd app sync frontend
          argocd app sync backend
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
      
      # Post CI/CD pipeline results to Google Chat
      - name: Send notification to Google Chat
        uses: googlechat/action@v1
        with:
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          message: |
            CI/CD Pipeline Result:
            - Build: ${{ job.status }}
